import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
// import "../styles/index.css";
import styles from "@/styles/index.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        style={{
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
          height: "100vh",
        }}
      >
        <Link href="/builder" className={styles.button}>
          Titan Builder
        </Link>
      </div>
    </>
  );
}
